### ISSUE TITLE
Website lists an empty list of ambitious people

### ISSUE THREAD

**Issue by lukaseder** [komunumo/komunumo.github.io#1]
The website https://komunumo.org refers to a list of "very ambitious people"

> Komunumo is being developed by a very ambitious [group of people](https://github.com/orgs/komunumo/people)

But that list of people is empty 😁

![image](https://user-images.githubusercontent.com/734593/121881339-70774400-cd0f-11eb-8727-4bd149127001.png)

I guess it's visible only to committers? I suggest to either:

- Make the list visible to everyone
- Remove the link

**Comment by McPringle** [comment]
Thanks for the hint! This was indeed a visibility issue. Should be fixed now. Would you like to join us? 🌈

**Comment by lukaseder** [comment]
> Would you like to join us?

Sure, why not? I can surely help with your jOOQ usage :)

**Comment by McPringle** [comment]
You are very welcome! I've created a Slack channel in the JUG workspace and send you an invite.

**Comment by lukaseder** [comment]
> I've created a Slack channel in the JUG workspace and send you an invite.

OK, but I hope this won't lead to too many notifications on my side? I mean, I can help with jOOQ usage, but otherwise, I don't think I'll participate in this very much - time being scarce etc.

**Comment by McPringle** [comment]
You don't need to join the Slack channel if you are worried about too many notifications. :-)
